=== E-Loubbidi/Bibliotheque_XML-XSL/biblio.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliotheque (livres, adherents, empreints) >
<!ELEMENT livres (livre*) >
<!ATTLIST livre isbn ID #REQUIRED >
<!ATTLIST livre code CDATA #REQUIRED >
<!ATTLIST livre datepublication CDATA  #REQUIRED>
<!ELEMENT livre (titre, description) >
<!ELEMENT  titre (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT adherents (adherent*) >
<!ELEMENT adherent (nom, prenom) >
<!ATTLIST adherent id ID #REQUIRED >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT empreints (sortie | entree)* >
<!ELEMENT sortie EMPTY >
<!ATTLIST sortie date CDATA #REQUIRED >
<!ATTLIST sortie livre CDATA #REQUIRED >
<!ATTLIST sortie adherent CDATA #REQUIRED >
<!ELEMENT entree EMPTY >
<!ATTLIST entree date CDATA #REQUIRED >
<!ATTLIST entree livre CDATA #REQUIRED >
<!ATTLIST entree adherent CDATA #REQUIRED >

=== E-Loubbidi/Bibliotheque_XML-XSL/biblio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliotheque SYSTEM "biblio.dtd">
<?xml-stylesheet type="text/xsl" href="abonnÃ©s.xsl"?>
<?xml-stylesheet type="text/xsl" href="livres.xsl"?>
<?xml-stylesheet type="text/xsl" href="empreints.xsl"?>
<?xml-stylesheet type="text/xsl" href="disponible.xsl"?>
<bibliotheque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblio.xsd">
    <livres>
        <livre isbn = "abcde" code = "abcde-120" datepublication = "2010-01-01">
            <titre>XML Faile</titre>
            <description>Apprendre XML en une heure</description>
        </livre>
        <livre isbn = "ijklm" code = "ijklm-320" datepublication = "2011-09-01">
            <titre>PHP Facile</titre>
            <description>Apprendre PHP en une heure</description>
        </livre>
        <livre isbn = "gtl" code = "gtl-120" datepublication = "2010-01-01">
            <titre>JAVA Facile</titre>
            <description>Apprendre JAVA en une heure</description>
        </livre>
        <livre isbn = "mnop" code = "mnop-320" datepublication = "2011-09-01">
            <titre>JS Facile</titre>
            <description>Apprendre JS en une heure</description>
        </livre>
    </livres>
    <adherents>
        <adherent id = "e-123">
            <nom>Raji</nom>
            <prenom>Mohammed</prenom>
        </adherent>
        <adherent id = "p-111">
            <nom>Maliki</nom>
            <prenom>Maha</prenom>
        </adherent>
    </adherents>
        <empreints>
            <sortie date = "2018/10/03" livre = "uvwxy-330" adherent = "e-123"/>
            <sortie date = "2018/10/04" livre = "ijklm-320" adherent = "p-111"/>
            <entree date = "2018/10/04" livre = "uvwxy-330" adherent = "e-123"/>
            <sortie date = "2018/10/05" livre = "mnop-320" adherent = "e-111"/>
            <entree date = "2018/10/05" livre = "ijklm-320" adherent = "e-123"/>
            <sortie date = "2018/10/06" livre = "ijklm-320" adherent = "e-111"/>
            <sortie date = "2018/10/08" livre = "mnop-320" adherent = "e-123"/>
            <sortie date = "2018/10/09" livre = "mnop-320" adherent = "p-111"/>
            <entree date = "2018/10/10" livre = "mnop-320" adherent = "p-333"/>
        </empreints>
</bibliotheque>
